"use client";
import { AnimatePresence, motion } from "framer-motion";
import { Heart, Music, Pause, Play, Sparkles, Volume2, VolumeX, ChevronRight, MapPin, Gift, RotateCcw, Star, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { gifts, letter, memories, profile, quizQuestions, secret } from "../data/story";

const pages = ["Start", "Quiz", "Moments", "Challenge", "Gifts", "Letter", "Celebrate"];
const transition = { initial:{opacity:0,y:22,scale:.985}, animate:{opacity:1,y:0,scale:1}, exit:{opacity:0,y:-22,scale:.985}, transition:{duration:.55} };

function Particles({ celebratory=false }: {celebratory?:boolean}) { return <div className="pointer-events-none fixed inset-0 overflow-hidden" aria-hidden>{Array.from({length: celebratory?40:18},(_,i)=><motion.span key={i} className="absolute text-pink-200/60" style={{left:`${(i*37)%100}%`,top:`${(i*53)%100}%`,fontSize: celebratory?10+(i%3)*7:8+(i%2)*6}} animate={{y:[0,-35,0],x:[0,(i%2?8:-8),0],rotate:[0,180,360],opacity:[.2,.8,.2]}} transition={{duration:4+(i%5),repeat:Infinity,delay:i*.13}}>{celebratory ? (i%3===0?"✦":"♥") : "•"}</motion.span>)}</div> }
function Primary({children,onClick,disabled=false}:{children:React.ReactNode,onClick:()=>void,disabled?:boolean}) { return <motion.button disabled={disabled} whileHover={{scale:1.035,y:-2}} whileTap={{scale:.97}} onClick={onClick} className="primary inline-flex min-h-14 items-center justify-center gap-2 rounded-full px-7 text-base font-semibold text-white disabled:cursor-not-allowed disabled:opacity-40">{children}<ChevronRight size={18}/></motion.button> }
function ImageOrPlaceholder({src,className=""}:{src:string,className?:string}) { const [bad,setBad]=useState(false); const chapterOne=src.includes("A59646AC-19A0-439E-8AF1-12773E512954.JPG"); const chapterTwo=src.includes("lp_image (2).jpeg"); const chapterThree=src.includes("F35E0B19-7A3D-49FD-9136-0E4AD7E4BC75"); const chapterFour=src.includes("182518DE-4FEF-4EEF-B486-9F26CD33A81B.JPG"); const chapterFive=src.includes("539C2B1B-05A1-4CF8-BB42-F5220454F6A6.JPG"); const giftOne=src.includes("A756E2C9-FCA5-424A-99CF-7CBF13800A30.JPG"); const giftThree=src.includes("D8747518-E895-4A1F-8524-949B6D01A200.JPG"); return <div className={`photo relative overflow-hidden ${className}`}>{!bad&&<img src={src} alt="A treasured memory" className="h-full w-full" style={{objectFit:giftOne?"contain":"cover",objectPosition:giftThree?"center 60%":chapterThree||chapterFour||chapterFive?"center center":chapterOne?"center 40%":chapterTwo?"center 30%":"center top"}} onError={()=>setBad(true)}/>} {bad&&<span className="absolute inset-0 grid place-items-center text-sm tracking-[.2em] text-white/70">YOUR PHOTO</span>}</div> }

export default function BirthdayExperience() {
 const [screen,setScreen]=useState(0), [music,setMusic]=useState(false), [muted,setMuted]=useState(false), [secretClicks,setSecretClicks]=useState(0), [secretOpen,setSecretOpen]=useState(false);
 const audio=useRef<HTMLAudioElement>(null);
 const go=(n:number)=>setScreen(n);
 const toggleMusic=()=>{const a=audio.current;if(!a)return; if(music){a.pause()}else{a.play().catch(()=>{});} setMusic(!music)};
 useEffect(()=>{if(audio.current) audio.current.muted=muted},[muted]);
 const onStar=()=>{setSecretClicks(v=>{if(v+1>=5)setSecretOpen(true);return v+1})};
 return <div className="ambient relative min-h-[100dvh] overflow-hidden"><audio ref={audio} loop src="/music/our-song.mp3"/>{screen>0&&<Progress screen={screen}/>}<Particles celebratory={screen===6}/><button onClick={onStar} className="absolute right-5 top-5 z-30 rounded-full p-2 text-pink-100/40 transition hover:text-pink-100" aria-label="A tiny star"><Star size={15}/></button>{screen>0&&<div className="fixed bottom-5 right-5 z-30 flex overflow-hidden rounded-full glass"><button onClick={toggleMusic} className="p-3" aria-label="Play or pause music">{music?<Pause size={18}/>:<Play size={18}/>}</button><button onClick={()=>setMuted(!muted)} className="border-l border-white/10 p-3" aria-label="Mute or unmute">{muted?<VolumeX size={18}/>:<Volume2 size={18}/>}</button></div>}
 <div className="grain absolute inset-0 opacity-20"/><AnimatePresence mode="wait"><motion.section key={screen} {...transition} className="relative z-10 mx-auto flex min-h-[100dvh] w-full max-w-6xl items-center px-5 py-20">{screen===0&&<Landing start={()=>{go(1);setTimeout(toggleMusic,20)}}/>}{screen===1&&<MemoryQuiz next={()=>go(2)}/>} {screen===2&&<Timeline next={()=>go(3)}/>} {screen===3&&<HeartGame next={()=>go(4)}/>} {screen===4&&<GiftBoxes next={()=>go(5)}/>} {screen===5&&<BirthdayLetter next={()=>go(6)}/>} {screen===6&&<Final replay={()=>go(0)}/>}</motion.section></AnimatePresence><AnimatePresence>{secretOpen&&<Secret close={()=>setSecretOpen(false)}/>}</AnimatePresence></div>
}
function Progress({screen}:{screen:number}){return <div className="fixed left-1/2 top-5 z-30 w-[min(84vw,360px)] -translate-x-1/2"><div className="mb-2 flex justify-between text-[10px] uppercase tracking-[.2em] text-pink-100/60"><span>Our story</span><span>{screen} / 6</span></div><div className="h-1 overflow-hidden rounded-full bg-white/10"><motion.div className="h-full rounded-full bg-gradient-to-r from-rose-300 to-violet-400" animate={{width:`${screen/6*100}%`}}/></div></div>}
function Landing({start}:{start:()=>void}){return <div className="mx-auto max-w-2xl text-center"><motion.div initial={{scale:0}} animate={{scale:1}} transition={{type:"spring"}} className="mx-auto mb-8 grid h-16 w-16 place-items-center rounded-full glass"><Heart className="fill-pink-300 text-pink-200"/></motion.div><p className="mb-5 text-xs uppercase tracking-[.35em] text-pink-200/70">A small story, made only for you</p><h1 className="serif text-6xl leading-[.9] sm:text-8xl">Hey, {profile.herName}</h1><p className="serif mx-auto mt-8 max-w-md text-2xl leading-relaxed text-pink-100/85">I made something for you.<br/>Ready?</p><div className="mt-11"><Primary onClick={start}><Sparkles size={19}/>Start the adventure</Primary></div><p className="mt-16 text-sm text-pink-100/55">Made with way too much effort <span className="text-pink-300">♥</span></p></div>}
function MemoryQuiz({next}:{next:()=>void}){const [q,setQ]=useState(0),[choice,setChoice]=useState<number|null>(null);const item=quizQuestions[q], done=choice!==null;const choose=(i:number)=>{if(!done)setChoice(i)};const continueQuiz=()=>{if(q===quizQuestions.length-1)next();else{setQ(q+1);setChoice(null)}};return <div className="mx-auto w-full max-w-2xl"><Label n="01" title="A little warm-up"/><h2 className="serif mt-4 text-4xl sm:text-5xl">Let’s see if you remember…</h2><div className="glass mt-9 rounded-[2rem] p-5 sm:p-8"><p className="text-sm text-pink-200/70">Question {q+1} of {quizQuestions.length}</p><h3 className="serif mt-4 text-2xl sm:text-3xl">{item.question}</h3><div className="mt-7 grid gap-3">{item.options.map((opt,i)=>{const selected=choice===i,correct=i===item.answer;return <motion.button whileTap={{scale:.985}} onClick={()=>choose(i)} key={opt} className={`rounded-2xl border px-5 py-4 text-left transition ${selected?(correct?"border-emerald-300 bg-emerald-300/15":"border-pink-300 bg-pink-300/15"):"border-white/10 bg-white/5 hover:border-pink-200/50"}`}>{opt}{done&&correct&&<span className="float-right text-emerald-200">✓</span>}</motion.button>})}</div>{done&&<motion.div initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="mt-6 rounded-2xl bg-pink-300/10 p-4 text-pink-50">{choice===item.answer?"Exactly. ":"That one was a sweet guess. "}{item.response}</motion.div>}<div className="mt-7 text-right"><Primary disabled={!done} onClick={continueQuiz}>{q===quizQuestions.length-1?"You actually remember":"Keep going"}</Primary></div></div></div>}
function Timeline({next}:{next:()=>void}){const [open,setOpen]=useState(0);const m=memories[open];return <div className="mx-auto w-full max-w-4xl"><Label n="02" title="Our little archive"/><h2 className="serif mt-4 text-4xl sm:text-5xl">Little moments that<br/>became everything</h2><div className="mt-10 grid gap-4 md:grid-cols-[.8fr_1.2fr]"> <div className="space-y-2">{memories.map((x,i)=><button key={x.title} onClick={()=>setOpen(i)} className={`flex w-full items-center gap-4 rounded-2xl p-4 text-left transition ${open===i?"glass":"hover:bg-white/5"}`}><span className="timeline-dot grid h-8 w-8 place-items-center rounded-full bg-pink-300 text-xs text-[#3b1835]">{i+1}</span><span><small className="block text-pink-200/50">{x.date}</small>{x.title}</span></button>)}</div><motion.div key={m.title} initial={{opacity:0,x:15}} animate={{opacity:1,x:0}} className="glass overflow-hidden rounded-[2rem]"><ImageOrPlaceholder src={m.image} className="h-52"/><div className="p-6"><p className="text-pink-200">{m.accent} {m.date}</p><h3 className="serif mt-2 text-3xl">{m.title}</h3><p className="mt-3 leading-relaxed text-pink-100/75">{m.description}</p><p className="mt-5 flex items-center gap-2 text-sm text-pink-200/65"><MapPin size={14}/>{m.location}</p></div></motion.div></div><div className="mt-9 text-center"><Primary onClick={next}>Okay, one little challenge</Primary></div></div>}
function HeartGame({next}:{next:()=>void}){const [playing,setPlaying]=useState(false),[score,setScore]=useState(0),[time,setTime]=useState(20),[hearts,setHearts]=useState<{id:number,x:number}[]>([]);useEffect(()=>{if(!playing)return;const tick=setInterval(()=>setTime(t=>t<=1?(clearInterval(tick),setPlaying(false),0):t-1),1000);const drop=setInterval(()=>setHearts(h=>[...h,{id:Date.now()+Math.random(),x:8+Math.random()*84}].slice(-14)),520);return()=>{clearInterval(tick);clearInterval(drop)}},[playing]);useEffect(()=>{const clean=setInterval(()=>setHearts(h=>h.slice(1)),1800);return()=>clearInterval(clean)},[]);const start=()=>{setScore(0);setTime(20);setHearts([]);setPlaying(true)};const msg=score>=30?"Okay, you win. You deserve the biggest birthday ever.":score>=20?"Someone’s pretty good at this.":score>=10?"Okayyyy, I see you 👀": "Every heart counts — especially the ones you give me.";return <div className="mx-auto w-full max-w-3xl text-center"><Label n="03" title="A tiny test of skill"/><h2 className="serif mt-4 text-4xl sm:text-5xl">Catch the hearts</h2><p className="mt-3 text-pink-100/70">Tap every heart before it floats away. You have 20 seconds.</p><div className="glass relative mt-8 h-[360px] overflow-hidden rounded-[2rem] border border-pink-200/20"><div className="absolute left-6 top-5 text-left"><p className="text-xs tracking-[.2em] text-pink-200/60">HEARTS</p><p className="serif text-4xl">{score}</p></div><div className="absolute right-6 top-5 text-right"><p className="text-xs tracking-[.2em] text-pink-200/60">TIME</p><p className="serif text-4xl">0:{String(time).padStart(2,"0")}</p></div>{hearts.map(h=><motion.button initial={{y:-50,opacity:0}} animate={{y:390,opacity:1}} transition={{duration:1.75,ease:"linear"}} key={h.id} onPointerDown={()=>{setScore(s=>s+1);setHearts(v=>v.filter(x=>x.id!==h.id))}} className="absolute top-0 -ml-5 touch-manipulation text-pink-300" style={{left:`${h.x}%`}} aria-label="Catch heart"><Heart size={36} fill="currentColor"/></motion.button>)}{!playing&&time===20&&<button onClick={start} className="absolute inset-0 grid place-items-center bg-[#1e1022]/35"><span className="primary rounded-full px-7 py-4 font-semibold">Start the game</span></button>}{!playing&&time===0&&<div className="absolute inset-0 grid place-items-center bg-[#1e1022]/55 p-6"><div><p className="serif text-3xl">You caught {score} hearts!</p><p className="mx-auto mt-3 max-w-sm text-pink-100/80">{msg}</p><div className="mt-6"><Primary onClick={next}>What’s next?</Primary></div></div></div>}</div></div>}
function GiftBoxes({next}:{next:()=>void}){const [opened,setOpened]=useState<number[]>([]);const [active,setActive]=useState<number|null>(null);const reveal=(i:number)=>{setOpened(x=>x.includes(i)?x:[...x,i]);setActive(i)};return <div className="mx-auto w-full max-w-4xl text-center"><Label n="04" title="Three tiny surprises"/><h2 className="serif mt-4 text-4xl sm:text-5xl">I have a few things for you…</h2><div className="mt-10 grid gap-5 sm:grid-cols-3">{gifts.map((g,i)=><motion.button key={g.title} whileHover={{y:-10,rotate:i===1?2:-2}} whileTap={{scale:.96}} onClick={()=>reveal(i)} className={`glass min-h-56 rounded-[2rem] p-6 text-left ${opened.includes(i)?"border-pink-200/60":""}`}><Gift className="mb-8 text-pink-200" size={35}/><p className="text-xs uppercase tracking-[.17em] text-pink-200/60">{g.label}</p><h3 className="serif mt-2 text-2xl">{opened.includes(i)?"Opened ✦":g.title}</h3><p className="mt-3 text-sm text-pink-100/55">Tap to unwrap</p></motion.button>)}</div>{opened.length===3&&<motion.div initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} className="mt-10"><p className="serif mb-4 text-2xl">You found everything…</p><Primary onClick={next}>One last thing</Primary></motion.div>}<AnimatePresence>{active!==null&&<GiftModal gift={gifts[active]} close={()=>setActive(null)}/>}</AnimatePresence></div>}
function GiftModal({gift,close}:{gift:(typeof gifts)[number],close:()=>void}){return <motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-40 grid place-items-center bg-[#130918]/75 p-5" onClick={close}><motion.div initial={{scale:.9,y:12}} animate={{scale:1,y:0}} exit={{scale:.9}} onClick={e=>e.stopPropagation()} className="glass relative max-w-md overflow-hidden rounded-[2rem] p-7 text-left"><button onClick={close} className="absolute right-5 top-5"><X/></button>{gift.image&&<ImageOrPlaceholder src={gift.image} className="mb-6 h-44 rounded-2xl"/>}<p className="text-sm uppercase tracking-[.2em] text-pink-200/65">{gift.title}</p><p className="serif mt-3 text-2xl leading-relaxed">{gift.message}</p></motion.div></motion.div>}
function BirthdayLetter({next}:{next:()=>void}){const [open,setOpen]=useState(false);return <div className="mx-auto w-full max-w-2xl text-center">{!open?<motion.div initial={{y:20,opacity:0}} animate={{y:0,opacity:1}} className="glass rounded-[2.5rem] p-10 sm:p-16"><div className="mx-auto mb-8 h-32 w-48 rounded-xl bg-gradient-to-br from-rose-200 to-fuchsia-300 shadow-2xl shadow-pink-500/30" style={{clipPath:"polygon(0 0,100% 0,100% 100%,50% 68%,0 100%)"}}/><p className="serif text-3xl">You have one unread letter.</p><div className="mt-8"><Primary onClick={()=>setOpen(true)}>Open it</Primary></div></motion.div>:<motion.article initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} className="glass rounded-[2rem] p-7 text-left sm:p-12"><p className="mb-7 text-xs uppercase tracking-[.24em] text-pink-200/60">For {profile.herName}, with love</p><div className="serif whitespace-pre-line text-lg leading-[1.85] text-pink-50 sm:text-xl">{letter}</div><div className="mt-9 text-center"><Primary onClick={next}>Turn the last page</Primary></div></motion.article>}</div>}
function Final({replay}:{replay:()=>void}){return <div className="mx-auto max-w-3xl text-center"><Sparkles className="mx-auto text-pink-200"/><h2 className="serif mt-6 text-5xl leading-tight sm:text-7xl">Happy Birthday,<br/>{profile.herName} <span className="text-pink-300">♥</span></h2><p className="mt-6 text-xl text-pink-100/80">Here’s to another year of being amazing.</p><div className="mt-10 grid grid-cols-2 gap-3 sm:grid-cols-4">{memories.slice(0,4).map(m=><ImageOrPlaceholder key={m.title} src={m.image} className="aspect-square rounded-2xl"/>)}</div><p className="serif mx-auto mt-10 max-w-xl text-2xl leading-relaxed text-pink-50">Some stories are better when they’re still being written…<br/><span className="text-pink-300">To be continued ♥</span></p><div className="mt-9"><Primary onClick={replay}><RotateCcw size={18}/>Replay our story</Primary></div></div>}
function Secret({close}:{close:()=>void}){return <motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-50 grid place-items-center bg-[#16091a]/85 p-5"><motion.div initial={{scale:.9}} animate={{scale:1}} className="glass relative max-w-md overflow-hidden rounded-[2rem] p-7 text-center"><button onClick={close} className="absolute right-4 top-4"><X/></button><ImageOrPlaceholder src={secret.image} className="mb-6 h-40 rounded-2xl"/><p className="serif text-3xl">{secret.message}</p><p className="mt-4 leading-relaxed text-pink-100/75">{secret.detail}</p></motion.div></motion.div>}
function Label({n,title}:{n:string,title:string}){return <p className="text-xs uppercase tracking-[.28em] text-pink-200/60">Chapter {n} · {title}</p>}
